// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	AuthorID  int32     `gorm:"column:author_id;not null" json:"author_id"`
	Body      string    `gorm:"column:body;not null" json:"body"`
	Path      string    `gorm:"column:path;not null" json:"path"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
