// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"time"
)

const TableNameReply = "reply"

// Reply mapped from table <reply>
type Reply struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	AuthorID  int32     `gorm:"column:author_id;not null" json:"author_id"`
	Body      string    `gorm:"column:body;not null" json:"body"`
	CommentID int32     `gorm:"column:comment_id;not null" json:"comment_id"`
}

// TableName Reply's table name
func (*Reply) TableName() string {
	return TableNameReply
}
