// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"time"
)

const TableNameServer = "server"

// Server mapped from table <server>
type Server struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	IsInit    int32     `gorm:"column:is_init;not null" json:"is_init"`
	APIKey    string    `gorm:"column:api_key;not null" json:"api_key"`
}

// TableName Server's table name
func (*Server) TableName() string {
	return TableNameServer
}
