info:
  contact: {}
  description: retalk api
  license:
    name: GPL 3.0
  title: retalk api
  version: "1.0"
paths:
  /healthz:
    get:
      description: 健康检查
      responses:
        "200":
          description: 返回健康状态
          schema:
            type: boolean
      summary: 健康检查
      tags:
      - 健康检查
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
