name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        run: corepack enable

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Lint
        run: nr lint

      - name: Gofumpt
        run: gofumpt -l -extra .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        run: corepack enable

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Typecheck
        run: nr typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        run: corepack enable

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build
