name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags -f

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20.4"

      - name: setup goreleaser
        run: |
          docker pull ghcr.io/goreleaser/goreleaser-cross:v1.20.4

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GH_TOKEN}}' > local/.release-env

      - name: build and release publish
        run: |
            docker run \
            --rm \
            --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/sysroot:/sysroot \
            -v $(pwd):/go/src/${PKG_NAME} \
            -w /go/src/${PKG_NAME} \
            -e CGO_ENABLED=1 \
            --env-file local/.release-env \
            ghcr.io/goreleaser/goreleaser-cross:v${GO_VERSION} \
            release --release-notes local/release-notes.md
