name: Release Build

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: git fetch --prune --unshallow --tags -f

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21.0

      - name: Setup Goreleaser
        run: |
          docker pull ghcr.io/goreleaser/goreleaser-cross:v1.21.0

      - name: Setup Environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GH_TOKEN}}' > .release-env
          echo VERSION=$(git describe --abbrev=0 --tags) > .sync-env

      - name: Build and release publish
        run: |
          docker run \
          --rm \
          --privileged \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/sysroot:/sysroot \
          -v $(pwd):/go/src/retalk \
          -w /go/src/retalk \
          -e CGO_ENABLED=1 \
          --env-file .release-env \
          ghcr.io/goreleaser/goreleaser-cross:v1.21.0 \
          release

  release-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
