name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: git fetch --prune --unshallow --tags -f

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20.4

      - name: Setup Goreleaser
        run: |
          docker pull ghcr.io/goreleaser/goreleaser-cross:v1.20.4

      - name: Setup Environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GH_TOKEN}}' > .release-env
          echo VERSION=$(git describe --abbrev=0 --tags) > .sync-env

      - name: Build and release publish
        run: |
          docker run \
          --rm \
          --privileged \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/sysroot:/sysroot \
          -v $(pwd):/go/src/retalk \
          -w /go/src/retalk \
          -e CGO_ENABLED=1 \
          --env-file .release-env \
          ghcr.io/goreleaser/goreleaser-cross:v1.20.4 \
          release
